### ISSUE TITLE
compiled failed on ubuntu14.04

### ISSUE THREAD

**Issue by shuzhenzhang** [ducha-aiki/mods#1]
hello,
Recently,i am learning mods, when i compiled mods on ubuntu14.04,but there are some problems occured,information  as follows:
[ 80%] Linking CXX executable mods
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_core.a(persistence.cpp.o): undefined reference to symbol 'gzclose'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: **\* [mods] ERROR 1
make[1]: **\* [CMakeFiles/mods.dir/all] ERROR 2
make: **\* [all] ERROR 2

I can not find what is the happen about it, could you give me some TIPS? thanks very much!

**Comment by LoveBaldwin** [comment]
sorry.

**Comment by ducha-aiki** [comment]
@shuzhenzhang hi,
it is very weird. What I have done, is create fresh Amazon instance with Ubuntu and followed my instructions. Which version of OpenCV do you use? Have installed it from apt-get get?

**Comment by shuzhenzhang** [comment]
@ducha-aiki hi,
thanks for your response! The OpenCV version is 2.4.9. For some objective reason，apt-get find no OpenCV, so I have to compile its source, then sudo make install.
And when i cmake .. ,information as follows:
shuzhen@shuzhen-Lenovo-Product:~/下载/mods-linux/build$ cmake ..
Looking for OpenCV
Not found!
-- A library with BLAS API found.
-- A library with LAPACK API found.
OpenMP found
OPENMP FOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /home/shuzhen/download/mods-linux/build

**Comment by ducha-aiki** [comment]
So it looks like CMake does not see OpenCV. Try to uncomment line in CMakeLists.txt
#SET (OpenCV_DIR "/usr/local/opencv-2.4.9/")
and set it to actual path to the directory containing FindOpenCV.cmake file

**Comment by shuzhenzhang** [comment]
@ducha-aiki hi,
I have tried in accordance with your advice,but failed angain.
It looks like no FindOpenCV.cmake file, so OPENCV_FOUND may be no-existent. It finds opencv using OpenCVConfig.cmake（config mode）.And I have tested opencv successed in my instance by "FIND_PACKAGE(OpenCV REQUIRED)".It is very weird!
Thanks again for your help!

**Comment by ducha-aiki** [comment]
I am afraid that I cannot reproduce your error :(

**Comment by shuzhenzhang** [comment]
@ducha-aiki hi，
I get it!
In mods-linux/detectors/mser/CMakeLists.txt,
IF(MODS_BUILD_SHARED)
TARGET_LINK_LIBRARIES(mser ${OpenCV_LIBS} rt)
ELSE(MODS_BUILD_SHARED)
TARGET_LINK_LIBRARIES(mser libopencv_imgproc.a libopencv_core.a rt)
ENDIF(MODS_BUILD_SHARED)
The opencv lib is *.so file, so "libopencv_imgproc.a libopencv_core.a" can not be found. Only TARGET_LINK_LIBRARIES(mser ${OpenCV_LIBS} rt)  is ok!
Thank you!

**Comment by ducha-aiki** [comment]
Comment out all of these, except TARGET_LINK_LIBRARIES(mser ${OpenCV_LIBS} rt)

**Comment by KoushikRaghav** [comment]
> hello,
> Recently,i am learning mods, when i compiled mods on ubuntu14.04,but there are some problems occured,information as follows:
> [ 80%] Linking CXX executable mods
> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_core.a(persistence.cpp.o): undefined reference to symbol 'gzclose'
> /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> make[2]: *** [mods] ERROR 1
> make[1]: *** [CMakeFiles/mods.dir/all] ERROR 2
> make: *** [all] ERROR 2
> 
> I can not find what is the happen about it, could you give me some TIPS? thanks very much!

can you provide step by step procedure in running the exe via terminal?
