### ISSUE TITLE
OpenCV 3.2?

### ISSUE THREAD

**Issue by hmongware** [ducha-aiki/mods#10]
Hello, great project.  Do you know if this project supports OpenCV 3.2?  If not, are there any plans to make it compatible with 3.2 or how can I compile it to use OpenCV 3.2?

**Comment by ducha-aiki** [comment]
Hi,
Currently it does not support OpenCV 3 and adopting it require lots of changes in 3rd party software (various author implementation of detectors and descriptors). So it is not in my close future plans.

**Comment by ducha-aiki** [comment]
But any help is appreciated :)
