### ISSUE TITLE
executable binaries

### ISSUE THREAD

**Issue by jbellic** [ducha-aiki/mods#11]
Can you please upload the compiled binaries for both linux and windows with the latest release code (2015 I assume)?

On the official page a 2015 binary version for linux is available but not the windows version.
It would be also very nice if you could upload the exctract features binaries separately for both win and linux.

Thanks in advance.

**Comment by ducha-aiki** [comment]
Windows version is already here at
https://github.com/ducha-aiki/mods/releases
Will upload linux version a bit later

**Comment by ducha-aiki** [comment]
Linux is there as well

**Comment by jbellic** [comment]
Thank you very much for the fast reply. Again many thanks for your efforts.

**Comment by jbellic** [comment]
Interestingly the 2016 compiled binaries don't match a easy example of two photos, whereas the 2013 version finds many matches. Also the new win release is missing both the default config files (iters.ini + config-iters.ini) and the libquadmath-0.dll file.

Unfortunately I have no luck in properly using the new binaries. Can you please have a look at it?
Didn't tested the linux version.

**Comment by ducha-aiki** [comment]
@tan-bur 
which version of Windows do you have? I have downloaded latest Windows binaries, unpacked in new folder and successfully matched example/cat.jpg and example/cat2.jpg .

As for the configs, as stated in example of usage in README.me https://github.com/ducha-aiki/mods/blob/linux/README.md, you should use config_iter_mods_cviu.ini and  iters_mods_cviu.ini

    mods.exe examples/cat.png examples/cat2.png out1.png out2.png k1.txt k2.txt m.txt l.txt 0 0 examples/cat.txt config_iter_mods_cviu.ini iters_mods_cviu.ini

**Comment by ducha-aiki** [comment]
Also, I am afraid, that cannot provide all possible standard libraries. Do you have mingw32 installed?

**Comment by ducha-aiki** [comment]
https://github.com/xianyi/OpenBLAS/issues/1112

**Comment by jbellic** [comment]
What I have done:

Download latest win binaries, extract to c:/, put missing dll files from your latest post (x64), put examples folder with cat images and run above script -> I get mods.exe application error: (0xc0000007b).
The old version still works perfectly.

**Comment by ducha-aiki** [comment]
What is your version of windows?

**Comment by jbellic** [comment]
Windows 10 x64

**Comment by ducha-aiki** [comment]
Please, post here copy-past of error message. 
Have you got libs from xianyi/OpenBLAS#1112 ?

**Comment by jbellic** [comment]
Unfortunately there is no error message except the mentioned above one. Yes I used the libs from the link. Should I reinstall the latest c++ redistributables?

**Comment by ducha-aiki** [comment]
The problem is that I cannot reproduce the bug :(
Have you tried to run mods.exe without options? Does it crash as well or produces help message?

**Comment by jbellic** [comment]
I tested the latest win release on a different windows machine and same issue is present. Even without options it's the same error message. The old version still works without any issues.

**Comment by ducha-aiki** [comment]
@tan-bur unfortunately, I cannot help you right now, because it works on my laptop. Will have opportunity next week. 
In mean time could you please try to compile it by instruction from readme?

**Comment by jbellic** [comment]
Ok, I will give it a try. Hope you also find something next week. Thanks.

**Comment by xiongxao** [comment]
@tan-bur, if you are able to compile from source; can you share the steps with me also?  I tried to compile from source, but was not able to (error at CMakeList.txt at line 29 "enable_language (Fortran)").  I tried to comment out line 29, but it errors out finding LAPACK packages, etc... 

My environment: 
- Windows 10, 64bit
- Visual Studio 2015, and 2017 64bit
- CMake 3.9.4 64bit (command line and GUI)
- Mingw 64bit (latest version)
- LAPACK 64bit (latest version)
- OpenCV 2.4.13.4

Thanks.

**Comment by jbellic** [comment]
Same issue here too with nearly same environment (error in CMakeList.txt:29).
I tried the binaries on a Windows 7 machine too, unfortunately the same issue. 
Maybe ducha-aiki has some good news :)

**Comment by ducha-aiki** [comment]
Try this https://github.com/ducha-aiki/mods/releases/tag/0.91a
Also, see https://github.com/ducha-aiki/mods/issues/12

**Comment by jbellic** [comment]
Hi,

thanks for the update. mods.exe can't be executed as nearly all libopencv dlls are missing. After putting in v249 libs, it asks for 248 versions aswell.

**Comment by ducha-aiki** [comment]
Here are OpenCV dlls, which I have on PC, which used for screenshot instruction creation https://drive.google.com/file/d/1NDfvlh5qG_sVBimDFLU9vmFM1e_le-SL/view?usp=sharing

If this doesn`t help, all I can suggest - to follow instructions in https://github.com/ducha-aiki/mods/issues/12

Lets make this straight: I am using Windows environment for programming only 3rd time in my life. First was at university 10 years ago and second - when I kind of ported this code in 2013 on Win XP or 7, don`t remember. So I am extremely not experienced in remote debugging, especially when I just cannot install library via simple apt-get install. Hope for understanding :)

There is 3rd possibility, actually - I have colleague, who knows Windows linking very well, but I would have opportunity to talk to him in only two weeks. So if everything still fail, I`ll try bring him here.
