### ISSUE TITLE
Compilation Fails on ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [ducha-aiki/mods#13]
When i write the comand "make" at build directory i got the following errors:

emiliano@emiliano-N53SM:~/feat_codigo/mods/build$ make[  0%] Building CXX object TILDE/c++/CMakeFiles/TILDE.dir/src/libTILDE.cpp.o
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In function ‘std::vector<cv::Mat> getLuv_fast(const cv::Mat&)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:73:3: error: ‘parallel_for’ is not a member of ‘cv’
   cv::parallel_for( cv::BlockedRange (0, input_color_image.rows), [=] (const cv
   ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:73:21: error: ‘BlockedRange’ is not a member of ‘cv’
   cv::parallel_for( cv::BlockedRange (0, input_color_image.rows), [=] (const cv
                     ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:73:82: error: ‘BlockedRange’ in namespace ‘cv’ does not name a type
 l_for( cv::BlockedRange (0, input_color_image.rows), [=] (const cv::BlockedRang
                                                                     ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In lambda function:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:128:7: error: expected ‘{’ before ‘;’ token
     });
       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In function ‘std::vector<cv::Mat> getLuv_fast(const cv::Mat&)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:128:7: error: expected ‘)’ before ‘;’ token
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:54:16: warning: unused variable ‘XYZ’ [-Wunused-variable]
   const double XYZ[3][3] = {  {  0.430574,  0.341550,  0.178325 },
                ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:58:16: warning: unused variable ‘Un_prime’ [-Wunused-variable]
   const double Un_prime   = 0.197833;
                ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:59:16: warning: unused variable ‘Vn_prime’ [-Wunused-variable]
   const double Vn_prime   = 0.468331;
                ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:61:16: warning: unused variable ‘minu’ [-Wunused-variable]
   const double minu   = -88*maxi;
                ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:62:16: warning: unused variable ‘minv’ [-Wunused-variable]
   const double minv   = -134*maxi;
                ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:63:16: warning: unused variable ‘Lt’ [-Wunused-variable]
   const double Lt     = 0.008856;
                ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In function ‘std::vector<cv::Mat> getGrad_fast(const cv::Mat&)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:177:3: error: ‘parallel_for’ is not a member of ‘cv’
   cv::parallel_for( cv::BlockedRange (0, gx[0].rows), [=] (const cv::BlockedRan
   ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:177:21: error: ‘BlockedRange’ is not a member of ‘cv’
   cv::parallel_for( cv::BlockedRange (0, gx[0].rows), [=] (const cv::BlockedRan
                     ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:177:70: error: ‘BlockedRange’ in namespace ‘cv’ does not name a type
  cv::parallel_for( cv::BlockedRange (0, gx[0].rows), [=] (const cv::BlockedRang
                                                                     ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In lambda function:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:222:7: error: expected ‘{’ before ‘;’ token
     });
       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In function ‘std::vector<cv::Mat> getGrad_fast(const cv::Mat&)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:222:7: error: expected ‘)’ before ‘;’ token
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In function ‘std::vector<cv::KeyPoint> getTILDEKeyPoints(const cv::Mat&, const string&, bool, bool, bool, cv::Mat*)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:256:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < curPart.size(); i++) {
                     ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In function ‘void getCombinedScore(const std::vector<std::vector<cv::Mat> >&, const bool&, cv::Mat*)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:365:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int idxCascade = 0; idxCascade < cascade_responses.size(); ++idxCascade)
                                       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:369:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int idxDepth = 1; idxDepth < cascade_responses[idxCascade].size(); +
                                       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In function ‘std::vector<cv::Point3_<float> > applyApproxFilters(const cv::Mat&, const TILDEobjects&, const std::vector<float>&, bool, bool, bool, cv::Mat*)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:465:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < res_with_score.size(); ++i) {
                     ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:433:15: warning: unused variable ‘scaleKeypoint’ [-Wunused-variable]
   const float scaleKeypoint = 10.0;const float orientation = 0;
               ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:433:48: warning: unused variable ‘orientation’ [-Wunused-variable]
   const float scaleKeypoint = 10.0;const float orientation = 0;
                                                ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In constructor ‘Parallel_process::Parallel_process(const std::vector<cv::Mat>&, int, const TILDEobjects&, std::vector<cv::Mat>&)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:483:25: warning: ‘Parallel_process::convt_image’ will be initialized after [-Wreorder]
   const vector < Mat > &convt_image;
                         ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:480:24: warning:   ‘const TILDEobjects& Parallel_process::cas’ [-Wreorder]
   const TILDEobjects & cas;
                        ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:486:3: warning:   when initialized here [-Wreorder]
   Parallel_process(const vector < Mat > &conv, const int nb, const TILDEobjects
   ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In function ‘std::vector<std::vector<cv::Mat> > getScoresForApprox(const TILDEobjects&, const std::vector<cv::Mat>&)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:540:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int idxFilter = 0; idxFilter < cas.filters.size() / 2; idxFilter++) {
                                     ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:519:7: warning: unused variable ‘nbOriginalFilters’ [-Wunused-variable]
   int nbOriginalFilters = nbMax * nbSum;
       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:521:7: warning: unused variable ‘nbChannels’ [-Wunused-variable]
   int nbChannels = param[4]; //6
       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:522:7: warning: unused variable ‘sizeFilters’ [-Wunused-variable]
   int sizeFilters = param[5]; //21
       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:532:7: warning: unused variable ‘idxSum’ [-Wunused-variable]
   int idxSum = 0;
       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:533:7: warning: unused variable ‘idxMax’ [-Wunused-variable]
   int idxMax = 0;
       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In function ‘void getScoresandCombine_Approx(const TILDEobjects&, const std::vector<cv::Mat>&, bool, cv::Mat*)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:613:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int idxFilter = 0; idxFilter < cas.filters.size() / 2; idxFilter++)
                                         ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:584:7: warning: unused variable ‘nbOriginalFilters’ [-Wunused-variable]
   int nbOriginalFilters = nbMax * nbSum;
       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:586:7: warning: unused variable ‘nbChannels’ [-Wunused-variable]
   int nbChannels = param[4]; //6
       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:587:7: warning: unused variable ‘sizeFilters’ [-Wunused-variable]
   int sizeFilters = param[5]; //21
       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:595:7: warning: unused variable ‘idxSum’ [-Wunused-variable]
   int idxSum = 0;
       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:596:7: warning: unused variable ‘idxMax’ [-Wunused-variable]
   int idxMax = 0;
       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:605:7: warning: unused variable ‘count’ [-Wunused-variable]
   int count = 0;
       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In function ‘std::vector<std::vector<lfilter> > getTILDENonApproxFilters(const string&, void*)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:663:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < tokens.size(); i++)
                       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:715:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (myCascade.size() == nbFilters) {
                            ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In function ‘std::vector<cv::Point3_<float> > applyNonApproxFilters(const cv::Mat&, const std::vector<std::vector<lfilter> >&, const std::vector<float>&, bool, bool, bool, cv::Mat*)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:780:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int idxCascade = 0; idxCascade < dual_cascade_filters.size(); ++idxCasca
                                       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:782:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int idxDepth = 0; idxDepth < dual_cascade_filters[idxCascade].size()
                                       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:789:47: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           for (int idxChannel = 0; idxChannel < cur_filter.w.size(); ++idxChann
                                               ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:803:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int idxCascade = 0; idxCascade < dual_cascade_filters.size(); ++idxCasca
                                       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:805:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int idxDepth = 1; idxDepth < dual_cascade_filters[idxCascade].size()
                                       ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:837:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < res_with_score.size(); ++i) {
                     ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In function ‘void Tokenize(const string&, std::vector<std::__cxx11::basic_string<char> >&, const string&, int, int)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:851:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (std::string::npos != p || std::string::npos != lp) {
                         ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:851:51: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (std::string::npos != p || std::string::npos != lp) {
                                                   ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In function ‘cv::Mat sumMatArray(const std::vector<cv::Mat>&)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:902:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int idxMat = 1; idxMat < MatArray.size(); ++idxMat) {
                               ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In function ‘TILDEobjects getTILDEApproxObjects(const string&, void*)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:1133:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i = 0; i < tokens.size(); i++) {
                         ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:1137:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i = 0; i < tokens.size(); i++) {
                         ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:1178:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (tokens.size() != nbOriginalFilters) {
                     ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:1183:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < tokens.size(); i++)
                     ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp: In function ‘cv::Mat getTILDEResponce(const cv::Mat&, const string&, bool, bool)’:
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:1299:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int idxCascade = 0; idxCascade < tilde_obj.nonApprox_filters.size();
                                           ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:1301:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           for (int idxDepth = 0; idxDepth < tilde_obj.nonApprox_filters[idxCasc
                                           ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:1308:51: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
               for (int idxChannel = 0; idxChannel < cur_filter.w.size(); ++idxC
                                                   ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:1321:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int idxCascade = 0; idxCascade < tilde_obj.nonApprox_filters.size();
                                           ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:1323:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           for (int idxDepth = 1; idxDepth < tilde_obj.nonApprox_filters[idxCasc
                                           ^
/home/emiliano/feat_codigo/mods/TILDE/c++/src/libTILDE.cpp:1276:17: warning: unused variable ‘sizeSmooth’ [-Wunused-variable]
       const int sizeSmooth = 5 * stdv * 2 + 1;
                 ^
TILDE/c++/CMakeFiles/TILDE.dir/build.make:62: fallo en las instrucciones para el objetivo 'TILDE/c++/CMakeFiles/TILDE.dir/src/libTILDE.cpp.o'
make[2]: *** [TILDE/c++/CMakeFiles/TILDE.dir/src/libTILDE.cpp.o] Error 1
CMakeFiles/Makefile2:1092: fallo en las instrucciones para el objetivo 'TILDE/c++/CMakeFiles/TILDE.dir/all'
make[1]: *** [TILDE/c++/CMakeFiles/TILDE.dir/all] Error 2
Makefile:127: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

Maybe i have to use different versions of gcc and opencv ?

**Comment by ducha-aiki** [comment]
Which version of OpenCV do you use?

**Comment by ghost** [comment]
Sorry, before i was using OpenCV 3. Now I've just installed OpenCV 2.4.9.  Now it compiles (with lots of warnings). I think the examples are running OK. Sorry to bother

**Comment by ducha-aiki** [comment]
You are welcome :)
