### ISSUE TITLE
Run mods exe without output image generation doesn't work

### ISSUE THREAD

**Issue by jbellic** [ducha-aiki/mods#15]
Unfortunately this still generates output images (which consumes time that I want to save):

- write log file only [0/1] -> this doesn't work

$ ./mods.exe img1.jpg img2.jpg out1.jpg out2.jpg m.txt l.txt **1** 0
*********************
Maximum threads can be used: 8
RootSIFT descriptor + LO-RANSAC (homography) verification are used.
View synthesis, detection and description...
*********************
Iteration 1
MSER: 3 view synthesis will be done
2873 keypoints detected in all views1 in step 1
2873 keypoints detected in all views2 in step 1
View synthesis, detection and description done in 1.806 seconds
RootSIFT FLANN joint matching...
Total: 2873 tentative correspondences are detected in 0.069 seconds
Duplicate filtering before RANSAC with threshold = 5 pixels.
1005 unique tentative correspondences left in 0.01 seconds
LO-RANSAC(homography) verification is used...
1005 true matches are identified in 0.01 seconds
Done in 1 iterations and 3 view synthesis
*********************
Writing files...
Image1: regions keypoints | Image2: regions keypoints
1354 2873 | 1354 2873

True matches | unique tentatives
1005 | 1005 | 100% RootSIFT 1st geom inc

Main matching | All Time:
1.96 | 5.21 seconds

**Comment by ducha-aiki** [comment]
@tan-bur sorry for it. 
If you don`t want output images, please use this flag in config_iter*.ini (whatever version of it you use):
```
[ImageOutput]
writeImages = 0
```
https://github.com/ducha-aiki/mods/blob/linux/build/config_iter_mods_cviu.ini#L173

**Comment by jbellic** [comment]
Thank you very much.

**Comment by jbellic** [comment]
One last question: Is it possible to exclude all outputs (incl. keys, matching and log file?) so pure matching runs faster?

- resolved -> there are also parameters in the config iter file. Im sorry.
