### ISSUE TITLE
Linux and Windows binaries behave strange with groundtruth param

### ISSUE THREAD

**Issue by jbellic** [ducha-aiki/mods#16]
mods.exe image1.jpg image2.jpg imgOut1.png imgOut2.png k1.txt k2.txt m.txt log.txt 1 0 config_iter_wxbs.ini iters_wxbs.ini

-> Results in succesful run in nearly 2 seconds (no groundTruth file specified)

mods.exe image1.jpg image2.jpg imgOut1.png imgOut2.png k1.txt k2.txt m.txt log.txt 1 0 gt.txt config_iter_wxbs.ini iters_wxbs.ini

-> Results in succesful run in nearly 16 seconds (although groundTruth usage is set to 0 = LORANSAC)

Whats also strange: On Linux (Ubuntu) running without specifying groundTruth file (even if it's set to 0) mods doesn't run (can't read iters config) but when specifying groundTruth file it runs too long.

Whats the issue? How do we run mods under linux without using groundTruth param and good performance?

Kind Regards.

**Comment by ducha-aiki** [comment]
Hi, 

Could you please provide images and tell me which version of code/binaries do you use?

**Comment by jbellic** [comment]
Hi,

sorry, everything works fine. I supplied the parameters in wrong order.
