### ISSUE TITLE
OpenCV version error

### ISSUE THREAD

**Issue by KoushikRaghav** [ducha-aiki/mods#18]
ERROR: Could not find a version that satisfies the requirement opencv==2.4.9 (from versions: none)
ERROR: No matching distribution found for opencv==2.4.9

**Comment by ducha-aiki** [comment]
You should install OpenCV then first

**Comment by ducha-aiki** [comment]
https://www.samontab.com/web/2014/06/installing-opencv-2-4-9-in-ubuntu-14-04-lts/
