### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by saransekar** [ducha-aiki/mods#19]
Kindly provide steps for Linux version

**Comment by ducha-aiki** [comment]
It is literally in README
https://github.com/ducha-aiki/mods#how-to-compile-mods-on-clean-ubuntu-1404-tested-on-amazon-aws-instance

**Comment by saransekar** [comment]
I'm unable to run in the terminal
How can I run without using wine? Any steps?

**Comment by ducha-aiki** [comment]
Why do you using wine? Just compile it from the source as instructions tell.
You could also try this binaries,  but the chances are you would be missing some libs
https://github.com/ducha-aiki/mods/releases/tag/19

**Comment by saransekar** [comment]
![export](https://user-images.githubusercontent.com/46147773/62598148-05d07280-b906-11e9-8563-c08f87348906.png)

**Comment by saransekar** [comment]
Getting this error. PLEASE guide me to run

**Comment by saransekar** [comment]
![export2](https://user-images.githubusercontent.com/46147773/62600021-64e4b600-b90b-11e9-8897-29f89896f0a7.png)


Generating is done, but still shows error

**Comment by saransekar** [comment]
Kindly guide me. Thanks in advance
