### ISSUE TITLE
How is the performance about the new features?

### ISSUE THREAD

**Issue by daleydeng** [ducha-aiki/mods#2]
Dear @ducha-aiki, I've learned your excellent work MODS on feature matching, I also saw there are some new features in this new commits compared with the previous downloaded one and reported on the paper, so how is the performance about the new one?

**Comment by ducha-aiki** [comment]
Thank you :)
The performance of the new features are explored in http://arxiv.org/abs/1504.06603 paper. As for this year papers, we are now working on huge benchmark paper, but it is not done yet.
