### ISSUE TITLE
Errors while compiling in windows 7 

### ISSUE THREAD

**Issue by kausic94** [ducha-aiki/mods#3]
Hello, Firstly great work with the paper. 

I followed the instructions as mentioned. I had openCV 2.4.13. I compiled it and in CMAKE and built using the MING32. I added the required details to PATH environment variable. I Then compiled the mods, setting the opencv/build/install directory as mentioned. The CMAKE finds openCV ,BLAS and LAPACK and openMP. So, Now when I run mingw32-make inside the build directory, it starts and after completition of a few percantage a bunch of error pop up.  

It says that in the file stat.h in mingw  '_dev_t', '_ino_t' and bunch of other variables are does not name a type. 

Then I reconfigured  by passing the -std=gnu++11 flag to cmake and I tried compiliing it . It says.
::fwide, ::mbsinit,::wcscat and other such varaibles have not been declared. the error comes from a file called  cwchar in Mingw which is being called by getExtrema.cpp in your program in the mser directory. 

Do help me out.

**Comment by ducha-aiki** [comment]
Hi,

Are you using latest g++? If yes, I am afraid, I haven`t experience with it :( Frankly speaking, what I have done to check if it works on Windows - installed clean Win7 on virtual machine, installed packages and fixed code until it worked.

I will try to help you, but some Windows machine will be available to me not earliest than next week :(

**Comment by kausic94** [comment]
thank you for your reply. And yes I downloaded mingw very recently. 

I tried building the code in ubuntu 14.04 as well. There was absolutely no hassel at while installing. But When I ran the example you gave I get 0 matches.  the output images have not keypoints marked like the ones you have shown.  Any suggestions on what to do.?

If it's possible could you make availble the binaries of the latest updated code. I believe the binaries you have made available in your website are old.

**Comment by ducha-aiki** [comment]
Could you please provide MODS console output? It could be that it finds correspondences and write it in log, but doesn`t output images/matches because it is switched off in the configuration file.

P.S. I can post the binaries on Monday-Tuesday.

**Comment by kausic94** [comment]
That would be wonderful if you can post the binaries. I am very thankful for your efforts.

I  am posting the output of the console output here when I run it on ubuntu. Do let me know if you find something that's not right.

> Maximum threads can be used: 4
> View synthesis, detection and description...
> Iteration 0
> ORB: 1 synthesis will be done.
> 272 , become 272
> ORB desc
> 300 , become 300
> ORB desc
> Matching ... 
> Matching ... 
> 0 0
> 0 tentatives found.
> Duplicate filtering before RANSAC with threshold = 2 pixels.
> 0 unique tentatives left
> Ground truth verification is used...
> 0 true matches got
> 0 RANSAC matches are identified in 0 seconds
> 0 RANSAC true matches are identified in 0 seconds
> 0 true matches are identified in 0 seconds
> Iteration 1
> ORB: 6 synthesis will be done.
> 98 , become 98
> ORB desc
> 45 , become 45
> ORB desc
> 19 , become 19
> ORB desc
> 44 , become 44
> ORB desc
> 25 , become 25
> ORB desc
> 8 , become 8
> ORB desc
> 29 , become 29
> ORB desc
> 29 , become 29
> ORB desc
> 33 , become 15
> ORB desc
> 45 , become 38
> ORB desc
> 22 , become 19
> ORB desc
> 22 , become 18
> ORB desc
> Matching ... 
> Matching ... 
> 423 536
> 416 tentatives found.
> Duplicate filtering before RANSAC with threshold = 2 pixels.
> 293 unique tentatives left
> Ground truth verification is used...
> 0 true matches got
> 0 RANSAC matches are identified in 0.242 seconds
> 0 RANSAC true matches are identified in 0.242 seconds
> 0 true matches are identified in 0.243 seconds
> Iteration 2
> MSER: 3 synthesis will be done.
> 11 , become 11
> 4 , become 4
> 6 , become 5
> 10 , become 10
> 7 , become 7
> 1 , become 1
> Matching ... 
> Matching ... 
> 10 20
> Matching ... 
> 0 0
> 7 tentatives found.
> Duplicate filtering before RANSAC with threshold = 2 pixels.
> 6 unique tentatives left
> Ground truth verification is used...
> 0 true matches got
> 0 RANSAC matches are identified in 0 seconds
> 0 RANSAC true matches are identified in 0 seconds
> 0 true matches are identified in 0 seconds
> Iteration 3
> MSER: 24 synthesis will be done.
> 11 , become 11
> 13 , become 11
> 8 , become 6
> 12 , become 12
> 6 , become 6
> 11 , become 11
> 9 , become 9
> 7 , become 6
> 7 , become 6
> 9 , become 7
> 9 , become 8
> 11 , become 9
> 9 , become 9
> 8 , become 8
> 6 , become 5
> 10 , become 8
> 6 , become 6
> 8 , become 7
> 4 , become 4
> 3 , become 3
> 8 , become 7
> 4 , become 3
> 9 , become 7
> 10 , become 8
> 9 , become 7
> 4 , become 4
> 7 , become 5
> 44 , become  , become 43
> 3 , become 2
> 5 , become 3
> 5 , become 5
> 3 , become 3
> 1 , become 1
> 4 , become 2
> 2 , become 2
> 3 , become 3
> 2 , become 1
> 1 , become 1
> 1 , become 1
> 4 , become 3
> 3 , become 2
> 2 , become 1
> 1 , become 0
> 4 , become 2
> 2 , become 1
> 3 , become 2
> 4 , become 1
> Matching ... 
> Matching ... 
> 73 118
> 52 tentatives found.
> Duplicate filtering before RANSAC with threshold = 2 pixels.
> 42 unique tentatives left
> Ground truth verification is used...
> 0 true matches got
> 21 RANSAC matches are identified in 0.002 seconds
> 0 RANSAC true matches are identified in 0.002 seconds
> 0 true matches are identified in 0.002 seconds
> Done in 4 iterations
> 
> ---
> 
> Writing files... 
> MSER 2
> ORB 2
> MSER 2
> ORB 2
> Image1: regions descriptors | Image2: regions descriptors 
> 565 496 | 668 654
> True matches | unique tentatives
> 0 | 42 | 0%  1st geom inc
> 0 | 21 | 0% RANSACed  1st geom inc
> Main matching | All Time: 
> 8.39 | 9.21 seconds
> Timings: (sec/%) 
> Synth|Detect|Orient|Desc|SCV|Match|RANSAC|MISC|Total 
> 6.99 0.86 0.0293 0.0906 0 0.031 0.245 0.969 9.21
> 75.8 9.34 0.318 0.983 0 0.337 2.66 10.5 100

**Comment by ducha-aiki** [comment]
Could you please also post command, which you execute? 

> Ground truth verification is used...

tells that you you ground truth verification, probably with random file. The default message is 

> LO-RANSAC(homography) verification is used...

**Comment by kausic94** [comment]
It was indeed the problem. I fixed it. Apologies for the late reply. dealing with internet issues.

P.S. Hope this would also serve as a gentle reminder regarding the binaries for windows.

**Comment by ducha-aiki** [comment]
@kausic94 https://github.com/ducha-aiki/mods/releases/tag/0.9

**Comment by kausic94** [comment]
Thank you.

**Comment by supriti-m** [comment]
Hi, 

I tried to use extract feature binary provided in https://github.com/ducha-aiki/mods/releases/tag/0.9 but I am getting error "the procedure entry point _zst24_throw_out_of_range_fmtPKcz could not be located in the dynamic link library libstdc++-6.dll"

Can you please help me to resolve this issue.

Thanks,
Supriti
