### ISSUE TITLE
Extract Feature execution Problem

### ISSUE THREAD

**Issue by supritimulay** [ducha-aiki/mods#4]
Hi,

I tried to use extract feature binary provided in https://github.com/ducha-aiki/mods/releases/tag/0.9 #3  but I am getting error "the procedure entry point _zst24_throw_out_of_range_fmtPKcz could not be located in the dynamic link library libstdc++-6.dll"

Can you please help me to resolve this issue.

Thanks,
Supriti

**Comment by supritimulay** [comment]
Can you please update on this issue. 

Thanks,
Supriti

**Comment by ducha-aiki** [comment]
@supriti-m I will try to add lib to release as soon, as I can. In the meantime you can try to download mingw32 and take this dll from it,

**Comment by supritimulay** [comment]
Thanks! I will try to take this dll from mingw32.

**Comment by ducha-aiki** [comment]
@supriti-m https://github.com/ducha-aiki/mods/releases/tag/0.91 - here is pack with two dlls from mingw32. COuld you please check it and tell me if it helps?

**Comment by supritimulay** [comment]
Thanks! Its working now.
