### ISSUE TITLE
matching without ground truth file 

### ISSUE THREAD

**Issue by supritimulay** [ducha-aiki/mods#5]
Hi,

I wanted to use the latest mods version to match the files without ground truth file. But on command line I am getting error 'Ground truth File is not specified'(which is parameter on command line). I am able to run the older version of MODS without ground truth file.  Is it possible to run the latest version of mods without ground truth file? 

Thanks,
Supriti

**Comment by ducha-aiki** [comment]
@supriti-m yes, you can. Just provide any filename there.
