### ISSUE TITLE
MODS failing for some images 

### ISSUE THREAD

**Issue by supritimulay** [ducha-aiki/mods#6]
Hi, 

I am using MODS for retinal image matching and it works fine for most of the images .For following two retinal image vessel extraction images MODS is failing with the error 
"This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information. 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc".

PFA images for your reference. 
![image_0_vessel](https://cloud.githubusercontent.com/assets/22741931/20999558/5a4fea80-bd3b-11e6-9c22-7639f4ee29db.png)
![image_3_vessel](https://cloud.githubusercontent.com/assets/22741931/20999559/5d2742bc-bd3b-11e6-82ca-26b7919d5c4d.png)

Can you please help me to sort out this issue.

Thanks,
Supriti

**Comment by ducha-aiki** [comment]
The most probable reason is that image is too big and you have memory problem. Try to set number of cores to 1 in config_iter.ini:
[Computing]
LoadColor=1;
numberOfCores=1

**Comment by supritimulay** [comment]
Thanks a lot!
