### ISSUE TITLE
Unable to run the precompiled Windows Version

### ISSUE THREAD

**Issue by deepak5g** [ducha-aiki/mods#7]
---------------------------
mods.exe - System Error
---------------------------
The program can't start because libgcc_s_dw2-1.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------

Getting the above error.

**Comment by ducha-aiki** [comment]
@deepak5g do you have mingw32 installed?

**Comment by deepak5g** [comment]
Yes I have installed Mingw32.

**Comment by deepak5g** [comment]
---------------------------
mods.exe - System Error
---------------------------
The program can't start because libquadmath-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------

And now I have surpassed that problem and got stuck here. any suggestions would be helpful?

**Comment by deepak5g** [comment]
Got it working now. I have manually downloaded the file and inserted in the mods path

**Comment by deepak5g** [comment]
unable to run the mods.exe getting the following error. OpenCV memory error, unable to allocate memory.

is there anything to be configured?

any help would be appreciated.

**Comment by ducha-aiki** [comment]
@deepak5g what is the size of images? If they are big, check this https://github.com/ducha-aiki/mods/issues/6

**Comment by deepak5g** [comment]
Yes! It is very high resolution, I have reduced the resolution, it seems running. but my match file seems empty or zero bytes. What I am missing?

**Comment by ducha-aiki** [comment]
@deepak5g could you please provide console log to avoid me trying to "oracle"?
If log shows there is a matches there, but no matches in match file, check if https://github.com/ducha-aiki/mods/blob/linux/build/config_iter_cviu.ini#L164 = 0. If 0, of course it will not write anything, so you need to change it to 1.

**Comment by deepak5g** [comment]
I got it working.. your configurations are very hard to understand. A proper documentation would help ppl like us to make use of it better. 

Thanks in advance.
