### ISSUE TITLE
extract features

### ISSUE THREAD

**Issue by deepak5g** [ducha-aiki/mods#9]
_./extract_features examples/cat.png cat1.txt config_iter_cviu.ini iters_mods_cviu_onestep.ini ./extract_features examples/cat2.png cat2.txt config_iter_cviu.ini iters_mods_cviu_onestep.ini_

I am following the above step, I am able to generate key descriptors and key points in the images, when trying to compare with the pre extracted key points with the below command, my result is either 0 or 100. MODS application getting crashed with bad_alloc error

_Now loading and matching ./mods examples/cat.png examples/cat2.png out1.png out2.png cat1.txt cat2.txt m.txt l.txt 0 1 examples/cat.txt config_iter_mods_cviu.ini iters_mods_cviu_onestep.ini 1_

**Comment by deepak5g** [comment]
Attaching my onestep ini file

[iters_mods_cviu_onestep.txt](https://github.com/ducha-aiki/mods/files/674354/iters_mods_cviu_onestep.txt)

**Comment by ducha-aiki** [comment]
@deepak5g Could you please attach console output logs? Unfortunately,  I cannot reproduce your error (here are my console logs):

> old-ufo@oldufo-UX303UB:/dev/tttt/mods/build$ ./extract_features examples/cat.png cat1.txt config_iter_cviu.ini iters_mods_cviu_onestep.ini View synthesis, detection and description...
0 , become 0
ORB desc
23 , become 23
ORB desc
13 , become 8
65 , become 65
ORB desc
260 , become 260
ORB desc
13 , become 10
ORB desc
31 , become 25
16 , become 10
16 , become 12
17 , become 8
15 , become 10
16 , become 12
ORB desc
11 , become 6
14 , become 9
7 , become 4
7 , become 5
6 , become 5
5 , become 3
4 , become 2
14 , become 11
2 , become 2
71 , become 68
5 , become 1
10 , become 6
3 , become 2
480 , become 480
ORB desc
1 , become 0
3 , become 2
1 , become 0
55 , become 36
126 , become 102
1 , become 0
2 , become 0
1 , become 0
221 , become 219
1 , become 0
202 , become 176
2 , become 1
255 , become 253
188 , become 160
14 , become 11
28 , become 18
118 , become 95
57 , become 48
44 , become 32
85 , become 78
155 , become 154
127 , become 110
145 , become 132
71 , become 57
36 , become 30
34 , become 18
7 , become 7
27 , become 17
11 , become 2
14 , become 10
16 , become 11
41 , become 34
26 , become 22
22 , become 16
47 , become 41
98 , become 90
119 , become 119
109 , become 104
62 , become 59
29 , become 23
19 , become 12
14 , become 8
13 , become 6
2 , become 2
22 , become 7
12 , become 3
9 , become 6
9 , become 8
12 , become 9
11 , become 3
16 , become 13
6 , become 5
22 , become 16
6 , become 1
25 , become 22
36 , become 32
84 , become 78
68 , become 68
67 , become 58
55 , become 50
24 , become 22
7 , become 3
6 , become 3
9 , become 5
6 , become 5
5 , become 2
8 , become 5
10 , become 2
11 , become 3
Writing files... 
HessianAffine 2
MSER 2
ORB 2
old-ufo@oldufo-UX303UB:/dev/tttt/mods/build$ ./extract_features examples/cat2.png cat2.txt config_iter_cviu.ini iters_mods_cviu_onestep.ini
View synthesis, detection and description...
159 , become 159
ORB desc
40 , become 40
ORB desc
426 , become 426
ORB desc
41 , become 28
ORB desc
0 , become 0
ORB desc
75 , become 53
69 , become 52
ORB desc
49 , become 31
91 , become 66
63 , become 45
44 , become 29
40 , become 24
46 , become 32
47 , become 29
29 , become 13
433 , become 432
13 , become 3
14 , become 5
14 , become 7
56 , become 37
12 , become 5
6 , become 1
500 , become 500
ORB desc
26 , become 15
9 , become 2
9 , become 3
3 , become 1
5 , become 1
99 , become 77
2 , become 0
6 , become 2
1 , become 0
10 , become 3
4 , become 1
4 , become 2
206 , become 204
414 , become 409
414 , become 358
270 , become 235
302 , become 301
377 , become 339
251 , become 208
295 , become 269
190 , become 170
97 , become 82
110 , become 96
77 , become 58
53 , become 50
83 , become 61
69 , become 47
72 , become 57
140 , become 121
222 , become 222
265 , become 242
221 , become 212
143 , become 134
85 , become 69
53 , become 45
58 , become 48
41 , become 35
35 , become 29
28 , become 25
35 , become 22
40 , become 28
41 , become 27
55 , become 47
30 , become 18
29 , become 22
24 , become 19
163 , become 163
208 , become 196
111 , become 101
155 , become 149
98 , become 94
72 , become 67
42 , become 34
34 , become 30
50 , become 40
32 , become 25
24 , become 20
28 , become 27
12 , become 11
20 , become 17
25 , become 20
31 , become 21
15 , become 7
9 , become 4
24 , become 14
24 , become 14
17 , become 12
11 , become 7
168 , become 160
19 , become 18
47 , become 44
76 , become 75
Writing files... 
HessianAffine 2
MSER 2
ORB 2
old-ufo@oldufo-UX303UB:~/dev/tttt/mods/build$ ./mods examples/cat.png examples/cat2.png out1.png out2.png cat1.txt cat2.txt m.txt l.txt 0 1 examples/cat.txt config_iter_mods_cviu.ini iters_mods_cviu_onestep.ini 1
Maximum threads can be used: 4
View synthesis, detection and description...
Iteration 0, loading pre-extracted features
numberOfDetectors=3
HessianAffine 2
None 2773 0
RootSIFT 2538 128
MSER 2
None 168 0
RootSIFT 130 128
ORB 2
None 850 0
ORB 850 32
numberOfDetectors=3
HessianAffine 2
None 6111 0
RootSIFT 5528 128
MSER 2
None 487 0
RootSIFT 366 128
ORB 2
None 1205 0
ORB 1205 32
Loading done
Matching ... 
Matching ... 
850 1205
Matching ... 
0 0
Matching ... 
0 0
Matching ... 
130 366
Matching ... 
0 0
Matching ... 
2538 5528
739 tentatives found.
Duplicate filtering before RANSAC with threshold = 2 pixels.
534 unique tentatives left
Ground truth verification is used...
97 true matches got
103 RANSAC matches are identified in 0.02 seconds
79 RANSAC true matches are identified in 0.02 seconds
97 true matches are identified in 0.02 seconds
Done in 1 iterations
>*********************
>Writing files... 
Image1: regions descriptors | Image2: regions descriptors 
3791 3518 | 7803 7099
True matches | unique tentatives
97 | 534 | 18.2%  1st geom inc
79 | 103 | 76.7% RANSACed  1st geom inc
Main matching | All Time: 
0.588 | 0.756 seconds
Timings: (sec/%) 
Synth|Detect|Orient|Desc|SCV|Match|RANSAC|MISC|Total 
0 0 0 0 0 0.199 0.02 0.537 0.756
0 0 0 0 0 26.3 2.65 71 100

**Comment by deepak5g** [comment]
mods.exe 4.jpeg IMG_4920.JPG Trial1.png Trial2.png key1.txt key2.txt mat.txt log.txt 0 0 cat.txt config_iter_mods_cviu.ini iters_mods_cviu.ini
View synthesis, detection and description...
Iteration 0
ORB: 1 synthesis will be done.
500 , become 500
ORB desc
500 , become 500
ORB desc
Matching ...
Matching ...
0 0
0 tentatives found.
Duplicate filtering before RANSAC with threshold = 2 pixels.
0 unique tentatives left
LO-RANSAC(homography) verification is used...
0 RANSAC correspondences got
0 true matches are identified in 0 seconds
Iteration 1
ORB: 6 synthesis will be done.
121 , become 121
ORB desc
307 , become 307
ORB desc
0 , become 0
ORB desc
126 , become 16
ORB desc
46 , become 46
ORB desc
57 , become 12
ORB desc
500 , become 500
ORB desc
497 , become 497
ORB desc
414 , become 414
ORB desc
480 , become 453
ORB desc
377 , become 377
ORB desc
477 , become 463
ORB desc
Matching ...
Matching ...
1002 3204
227 tentatives found.
Duplicate filtering before RANSAC with threshold = 2 pixels.
169 unique tentatives left
LO-RANSAC(homography) verification is used...
0 RANSAC correspondences got
0 true matches are identified in 0.053 seconds
Iteration 2
MSER: 3 synthesis will be done.
377 , become 365
93 , become 87
10 , become 8
511 , become 509
87 , become 86
20 , become 19
Matching ...
Matching ...
346 587
Matching ...
0 0
66 tentatives found.
Duplicate filtering before RANSAC with threshold = 2 pixels.
64 unique tentatives left
LO-RANSAC(homography) verification is used...
27 RANSAC correspondences got
27 true matches are identified in 0.008 seconds
Done in 3 iterations
*********************
Writing files...
MSER 2
ORB 2
MSER 2
ORB 2
Image1: regions descriptors | Image2: regions descriptors
1462 1348 | 3818 3791

True matches | unique tentatives
27 | 64 | 42.2%  1st geom inc

Main matching | All Time:
5.33 | 8.14 seconds
Timings: (sec/%)
Synth|Detect|Orient|Desc|SCV|Match|RANSAC|MISC|Total
3.5 0.859 0.0845 0.577 0 0.103 0.063 2.95 8.14
43 10.6 1.04 7.09 0 1.27 0.774 36.3 100

extract_features.exe 4.jpeg 4.txt config_iter_cviu.ini iters_mods_cviu_onestep.ini
View synthesis, detection and description...
1648 , become 1647
605 , become 605
790 , become 754
838 , become 822
766 , become 765
734 , become 726
756 , become 734
215 , become 214
314 , become 288
270 , become 234
224 , become 202
237 , become 227
348 , become 338
334 , become 333
264 , become 260
180 , become 175
150 , become 142
173 , become 156
274 , become 254
143 , become 143
199 , become 169
171 , become 139
142 , become 122
103 , become 96
102 , become 92
95 , become 89
219 , become 213
265 , become 259
220 , become 219
212 , become 209
138 , become 135
90 , become 85
50 , become 48
65 , become 60
76 , become 71
123 , become 109
145 , become 133
100 , become 99
133 , become 121
118 , become 102
127 , become 105
74 , become 60
49 , become 45
47 , become 46
42 , become 37
73 , become 67
106 , become 95
114 , become 111
99 , become 94
76 , become 76
87 , become 85
69 , become 66
68 , become 65
60 , become 58
58 , become 55
44 , become 38
35 , become 28
51 , become 42
52 , become 38
79 , become 68
99 , become 97
377 , become 365
256 , become 246
187 , become 170
175 , become 158
148 , become 140
83 , become 57
93 , become 84
92 , become 86
56 , become 47
93 , become 87
15 , become 5
7 , become 1
6 , become 1
5 , become 0
7 , become 1
4 , become 0
2 , become 0
6 , become 0
10 , become 8
5 , become 0
0 , become 0
2 , become 0
1 , become 0
0 , become 0
1 , become 0
0 , become 0
0 , become 0
500 , become 500
ORB desc
121 , become 121
ORB desc
307 , become 307
ORB desc
0 , become 0
ORB desc
126 , become 16
ORB desc
46 , become 46
ORB desc
57 , become 12
ORB desc
Writing files...
HessianAffine 2
MSER 2
ORB 2

extract_features.exe IMG_4920.JPG IMG_4920.txt config_iter_cviu.ini iters_mods_cviu_onestep.ini
View synthesis, detection and description...
1214 , become 1214
652 , become 651
758 , become 724
732 , become 684
677 , become 675
760 , become 728
680 , become 642
283 , become 282
403 , become 374
449 , become 428
388 , become 362
304 , become 290
312 , become 288
333 , become 332
414 , become 390
399 , become 380
361 , become 339
295 , become 269
266 , become 240
170 , become 170
255 , become 237
288 , become 272
356 , become 341
291 , become 274
198 , become 191
163 , become 158
146 , become 142
212 , become 192
216 , become 215
219 , become 199
247 , become 236
239 , become 234
212 , become 202
196 , become 190
169 , become 159
138 , become 126
152 , become 128
98 , become 98
119 , become 111
168 , become 156
264 , become 250
311 , become 293
219 , become 206
151 , become 143
91 , become 87
88 , become 87
108 , become 106
128 , become 123
141 , become 131
157 , become 156
178 , become 164
152 , become 144
189 , become 181
155 , become 150
131 , become 130
129 , become 126
146 , become 142
115 , become 107
94 , become 83
106 , become 95
96 , become 71
511 , become 509
282 , become 278
143 , become 140
149 , become 147
139 , become 136
89 , become 86
106 , become 102
99 , become 96
104 , become 101
87 , become 86
26 , become 25
14 , become 13
16 , become 14
10 , become 8
10 , become 8
16 , become 12
13 , become 12
10 , become 6
20 , become 19
7 , become 6
4 , become 3
5 , become 3
9 , become 6
4 , become 3
7 , become 3
6 , become 6
5 , become 3
500 , become 500
ORB desc
500 , become 500
ORB desc
497 , become 497
ORB desc
414 , become 414
ORB desc
480 , become 453
ORB desc
377 , become 377
ORB desc
477 , become 463
ORB desc
Writing files...
HessianAffine 2
MSER 2
ORB 2


mods.exe 4.jpeg IMG_4920.JPG Trial21.png Trial22.png 4.txt IMG_4920.txt mat.txt log.txt 0 1 homography.txt config_iter_mods_cviu.ini iters_mods_cviu_onestep.ini 1
View synthesis, detection and description...
Iteration 0, loading pre-extracted features
numberOfDetectors=3
HessianAffine 2
None 12965 0
RootSIFT 11375 128
MSER 2
None 1456 0
RootSIFT 1090 128
ORB 2
None 1002 0
ORB 1002 32
numberOfDetectors=3
HessianAffine 2
None 16298 0
RootSIFT 15857 128
MSER 2
None 1831 0
RootSIFT 1700 128
ORB 2
None 3204 0
ORB 3204 32
Loading done
Matching ...
Matching ...
1002 3204
Matching ...
0 0
Matching ...
0 0
Matching ...
1090 1700
Matching ...
0 0
Matching ...
11375 15857
1621 tentatives found.
Duplicate filtering before RANSAC with threshold = 2 pixels.
1373 unique tentatives left
Ground truth verification is used...
0 true matches got
383 RANSAC matches are identified in 0.061 seconds
0 RANSAC true matches are identified in 0.061 seconds
0 true matches are identified in 0.063 seconds
Done in 1 iterations
*********************
Writing files...
Image1: regions descriptors | Image2: regions descriptors
15423 13467 | 21333 20761

True matches | unique tentatives
0 | 1373 | 0%  1st geom inc
0 | 383 | 0% RANSACed  1st geom inc

Main matching | All Time:
40.1 | 40.8 seconds
Timings: (sec/%)
Synth|Detect|Orient|Desc|SCV|Match|RANSAC|MISC|Total
0 0 0 0 0 1.28 0.064 39.5 40.8
0 0 0 0 0 3.14 0.157 96.7 100

**Comment by deepak5g** [comment]
**This is for the example files you had provided with the build**

extract_features.exe examples/cat.png cat1.txt config_iter_cviu.ini iters_mods_cviu_onestep.ini
View synthesis, detection and description...
255 , become 253
71 , become 68
126 , become 102
202 , become 176
221 , become 219
188 , become 160
118 , become 95
14 , become 11
28 , become 18
44 , become 32
56 , become 48
85 , become 78
127 , become 110
155 , become 154
145 , become 132
71 , become 57
36 , become 30
27 , become 17
34 , become 18
7 , become 7
11 , become 2
14 , become 10
16 , become 11
22 , become 16
26 , become 22
41 , become 34
47 , become 41
98 , become 90
119 , become 119
109 , become 104
62 , become 59
29 , become 23
19 , become 12
14 , become 8
9 , become 6
13 , become 6
22 , become 7
2 , become 2
12 , become 3
6 , become 1
11 , become 3
12 , become 9
9 , become 8
6 , become 5
16 , become 13
22 , become 16
25 , become 22
36 , become 32
67 , become 58
68 , become 68
84 , become 78
55 , become 50
24 , become 22
7 , become 3
6 , become 3
9 , become 5
6 , become 5
8 , become 5
4 , become 2
11 , become 3
10 , become 2
55 , become 36
31 , become 25
13 , become 8
16 , become 12
14 , become 11
16 , become 10
15 , become 10
17 , become 8
14 , become 9
11 , become 6
7 , become 4
7 , become 5
6 , become 5
5 , become 3
4 , become 2
2 , become 2
5 , become 1
3 , become 2
10 , become 6
3 , become 2
1 , become 0
2 , become 0
1 , become 0
1 , become 0
1 , become 0
2 , become 1
1 , become 0
480 , become 480
ORB desc
23 , become 23
ORB desc
260 , become 260
ORB desc
0 , become 0
ORB desc
13 , become 10
ORB desc
65 , become 65
ORB desc
16 , become 12
ORB desc
Writing files...
HessianAffine 2
MSER 2
ORB 2

extract_features.exe examples/cat2.png cat2.txt config_iter_cviu.ini iters_mods_cviu_onestep.ini
View synthesis, detection and description...
414 , become 409
433 , become 432
414 , become 358
270 , become 235
205 , become 203
251 , become 208
377 , become 339
302 , become 301
295 , become 269
190 , become 170
110 , become 96
97 , become 82
77 , become 58
53 , become 50
83 , become 61
69 , become 47
72 , become 57
140 , become 121
265 , become 242
222 , become 222
222 , become 213
142 , become 133
85 , become 69
58 , become 48
53 , become 45
41 , become 35
35 , become 29
40 , become 28
29 , become 26
35 , become 22
41 , become 27
30 , become 18
29 , become 22
24 , become 19
55 , become 47
111 , become 101
208 , become 196
163 , become 163
155 , become 149
98 , become 94
72 , become 67
49 , become 39
42 , become 34
34 , become 30
32 , become 25
24 , become 20
28 , become 27
25 , become 20
20 , become 17
12 , become 11
15 , become 7
31 , become 21
24 , become 14
24 , become 14
17 , become 12
9 , become 4
11 , become 7
19 , become 18
47 , become 44
76 , become 75
168 , become 160
99 , become 77
91 , become 66
75 , become 53
49 , become 31
56 , become 37
63 , become 45
44 , become 29
40 , become 24
47 , become 29
46 , become 32
29 , become 13
13 , become 3
14 , become 5
14 , become 7
12 , become 5
9 , become 2
6 , become 1
10 , become 3
26 , become 15
9 , become 3
3 , become 1
6 , become 2
5 , become 1
2 , become 0
4 , become 1
1 , become 0
4 , become 2
500 , become 500
ORB desc
426 , become 426
ORB desc
40 , become 40
ORB desc
159 , become 159
ORB desc
69 , become 52
ORB desc
0 , become 0
ORB desc
41 , become 28
ORB desc
Writing files...
HessianAffine 2
MSER 2
ORB 2

mods.exe examples/cat.png examples/cat2.png out1.png out2.png cat1.txt cat2.txt m.txt l.txt 0 1 examples/cat.txt config_iter_mods_cviu.ini iters_mods_cviu_onestep.ini 1
View synthesis, detection and description...
Iteration 0, loading pre-extracted features
numberOfDetectors=3
HessianAffine 2
None 2773 0
RootSIFT 2538 128
MSER 2
None 168 0
RootSIFT 130 128
ORB 2
None 850 0
ORB 850 32
numberOfDetectors=3
HessianAffine 2
None 6110 0
RootSIFT 5528 128
MSER 2
None 487 0
RootSIFT 366 128
ORB 2
None 1205 0
ORB 1205 32
Loading done
Matching ...
Matching ...
850 1205
Matching ...
0 0
Matching ...
0 0
Matching ...
130 366
Matching ...
0 0
Matching ...
2538 5528
753 tentatives found.
Duplicate filtering before RANSAC with threshold = 2 pixels.
548 unique tentatives left
Ground truth verification is used...
0 true matches got
103 RANSAC matches are identified in 0.072 seconds
0 RANSAC true matches are identified in 0.072 seconds
0 true matches are identified in 0.074 seconds
Done in 1 iterations
*********************
Writing files...
Image1: regions descriptors | Image2: regions descriptors
3791 3518 | 7802 7099

True matches | unique tentatives
0 | 548 | 0%  1st geom inc
0 | 103 | 0% RANSACed  1st geom inc

Main matching | All Time:
12 | 12.3 seconds
Timings: (sec/%)
Synth|Detect|Orient|Desc|SCV|Match|RANSAC|MISC|Total
0 0 0 0 0 0.312 0.074 11.9 12.3
0 0 0 0 0 2.54 0.603 96.9 100

mods.exe examples/cat.png examples/cat2.png out1.png out2.png cat1.txt cat2.txt m.txt l.txt 0 0 examples/cat.txt config_iter_mods_cviu.ini iters_mods_cviu.ini
View synthesis, detection and description...
Iteration 0
ORB: 1 synthesis will be done.
480 , become 480
ORB desc
500 , become 500
ORB desc
Matching ...
Matching ...
0 0
0 tentatives found.
Duplicate filtering before RANSAC with threshold = 2 pixels.
0 unique tentatives left
LO-RANSAC(homography) verification is used...
0 RANSAC correspondences got
0 true matches are identified in 0.002 seconds
Iteration 1
ORB: 6 synthesis will be done.
23 , become 23
ORB desc
260 , become 260
ORB desc
0 , become 0
ORB desc
13 , become 10
ORB desc
65 , become 65
ORB desc
16 , become 12
ORB desc
426 , become 426
ORB desc
40 , become 40
ORB desc
159 , become 159
ORB desc
69 , become 52
ORB desc
0 , become 0
ORB desc
41 , become 28
ORB desc
Matching ...
Matching ...
850 1205
507 tentatives found.
Duplicate filtering before RANSAC with threshold = 2 pixels.
337 unique tentatives left
LO-RANSAC(homography) verification is used...
0 RANSAC correspondences got
0 true matches are identified in 0.065 seconds
Iteration 2
MSER: 3 synthesis will be done.
55 , become 36
11 , become 6
10 , become 6
99 , become 77
46 , become 32
26 , become 15
Matching ...
Matching ...
39 93
Matching ...
0 0
2 tentatives found.
Duplicate filtering before RANSAC with threshold = 2 pixels.
2 unique tentatives left
LO-RANSAC(homography) verification is used...
0 RANSAC correspondences got
0 true matches are identified in 0.002 seconds
Iteration 3
MSER: 24 synthesis will be done.
31 , become 25
13 , become 8
16 , become 12
14 , become 11
16 , become 10
15 , become 10
17 , become 8
14 , become 9
7 , become 4
7 , become 5
6 , become 5
5 , become 3
4 , become 2
2 , become 2
5 , become 1
3 , become 2
3 , become 2
1 , become 0
2 , become 0
1 , become 0
1 , become 0
1 , become 0
2 , become 1
1 , become 0
91 , become 66
75 , become 53
49 , become 31
56 , become 37
63 , become 45
44 , become 29
40 , become 24
47 , become 29
29 , become 13
13 , become 3
14 , become 5
14 , become 7
12 , become 5
9 , become 2
6 , become 1
10 , become 3
9 , become 3
3 , become 1
6 , become 2
5 , become 1
2 , become 0
4 , become 1
1 , become 0
4 , become 2
Matching ...
Matching ...
132 351
8 tentatives found.
Duplicate filtering before RANSAC with threshold = 2 pixels.
8 unique tentatives left
LO-RANSAC(homography) verification is used...
0 RANSAC correspondences got
0 true matches are identified in 0.002 seconds
Iteration 4
HessianAffine: 11 synthesis will be done.
255 , become 253
71 , become 68
14 , become 11
155 , become 154
7 , become 7
41 , become 34
29 , become 23
2 , become 2
6 , become 5
68 , become 68
9 , become 5
414 , become 409
433 , become 432
302 , become 301
52 , become 49
222 , become 222
41 , become 35
30 , become 18
163 , become 163
34 , become 30
12 , become 11
9 , become 4
Matching ...
Matching ...
556 1521
52 tentatives found.
Duplicate filtering before RANSAC with threshold = 2 pixels.
50 unique tentatives left
LO-RANSAC(homography) verification is used...
20 RANSAC correspondences got
20 true matches are identified in 0.009 seconds
Done in 5 iterations
*********************
Writing files...
HessianAffine 2
MSER 2
ORB 2
HessianAffine 2
MSER 2
ORB 2
Image1: regions descriptors | Image2: regions descriptors
1648 1538 | 3366 3077

True matches | unique tentatives
20 | 50 | 40%  1st geom inc

Main matching | All Time:
9.66 | 12.3 seconds
Timings: (sec/%)
Synth|Detect|Orient|Desc|SCV|Match|RANSAC|MISC|Total
6.97 1.31 0.249 0.833 0 0.124 0.083 2.69 12.3
56.8 10.7 2.03 6.79 0 1.01 0.677 22 100

**When I run individually the matches are coming, but with extract features it is not working**

**Comment by deepak5g** [comment]
The text files holding key points differs when using extract features. It has only 10% of actual key points when using mods

**Comment by ducha-aiki** [comment]
@deepak5g thanks for catch!

The difference in # of keypoint caused by that for "mods" you use other .ini file - iters_mods_cviu.ini instead of iters_mods_cviu_onestep.ini. First one - iters_mods_cviu.ini - does iterative matching until 20 matches are found. 
iters_mods_cviu_onestep.ini does first extraction everything possible, then matching - that is why big overhead in features number and more matches.

As for the problem with extract features - I cannot find problem source so far. Linux version works, while WIndows one - which is ported - somehow not. Will investigate this issue and answer later. 

So far I can propose two temporal solutions - use plain mods.exe or switch to Linux version.

**Comment by deepak5g** [comment]
@ducha-aiki Thanks for the information, I will try with Linux version. Also looking forward from you the updated Windows version.
